# Site settings
title: Junghyeon Ahn
email: ro033026@gmail.com
description: "Data Analyst portfolio"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

linkedin_username: "Junghyeon-ahn"
instagram_username: "hyeon_1998_"

# Build settings
markdown: kramdown
